"""
Configuration module for human-cognition-ai.

This module provides centralized configuration including file paths,
model settings, and other shared constants.
"""

from .paths import (
    KNOWLEDGE_DIR,
    EVOLUTION_DIR,
    TRAINING_DATA_FILE,
    LEARNED_HASHES_FILE,
    BENCHMARK_HISTORY_FILE,
    EVOLUTION_STATE_FILE,
    ADAPTERS_DIR,
    LLAMA_FACTORY_OUTPUT_DIR,
    MLX_MODEL_PATH,
    HF_MODEL_PATH,
    LM_STUDIO_URL,
    DEFAULT_MODEL,
    ensure_directories,
)

from .constants import (
    # Memory Forgetting Constants
    DEFAULT_DECAY_RATE,
    REHEARSAL_BOOST_MULTIPLIER,
    MIN_ACTIVATION_THRESHOLD,
    BASE_STABILITY_HOURS,
    STABILITY_MULTIPLIER,
    MIN_STABILITY_HOURS,
    MAX_STABILITY_HOURS,
    FORGET_RETENTION_THRESHOLD,
    IMMEDIATE_REVIEW_DELAY_HOURS,
    # Active Learning Constants
    EXPOSURE_DECAY_RATE,
    UNCERTAINTY_PRIORITY_WEIGHT,
    CURIOSITY_PRIORITY_WEIGHT,
    NOVELTY_PRIORITY_WEIGHT,
    DEFAULT_TOPIC_CONFIDENCE,
    DEFAULT_TOPIC_CURIOSITY,
    RND_CURIOSITY_WEIGHT,
    RND_HIGH_CURIOSITY_THRESHOLD,
    LOW_CURIOSITY_THRESHOLD,
    KNOWN_TOPIC_PRIORITY_FACTOR,
    DEFAULT_CURIOSITY_BOOST,
    HIGH_CONFIDENCE_THRESHOLD,
    CURIOSITY_DECAY_WEIGHT,
    CURIOSITY_UPDATE_WEIGHT,
    # Bayesian Surprise Constants
    SURPRISE_WINDOW_SIZE,
    SURPRISE_ENCODING_THRESHOLD,
    MIN_SURPRISE_OBSERVATIONS,
    SURPRISE_SMOOTHING_ALPHA,
    BAYESIAN_SURPRISE_PERCENTILE,
    DEFAULT_OBSERVATION_VARIANCE,
    # Episodic Memory Constants
    DEFAULT_EPISODE_IMPORTANCE,
    IMPORTANCE_DECAY_FACTOR,
    FORGETTING_BACKGROUND_INTERVAL_SECONDS,
    REVIEW_RETENTION_THRESHOLD,
    FORGETTING_THREAD_TIMEOUT_SECONDS,
    HIGH_IMPORTANCE_THRESHOLD,
    INITIAL_RETENTION_BASE,
    INITIAL_RETENTION_IMPORTANCE_FACTOR,
    IMPORTANCE_SIGMOID_OFFSET,
    # Numerical Stability Constants
    EXP_CLIP_MIN,
    EXP_CLIP_MAX,
    EPSILON,
    DEFAULT_SUCCESS_RATE,
    # Predictive Model Constants
    DEFAULT_LSTM_HIDDEN_DIM,
    DEFAULT_LSTM_NUM_LAYERS,
    LSTM_DROPOUT_RATE,
    # Demo/Test Constants
    DEMO_SURPRISE_MULTIPLIER,
)
